a = int(input())
b = int(input())
c = int(input())
if(a + b < c or a + c < b or b + c < a): print('Not a triangle')
elif(a == b and b == c): print('Equilateral triangle') 
elif(a == b or b == c or a == c): print('Isosceles triangle')
else: print('Ordinary triangle')